version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file: .env
    network_mode: host
    command: --bind-address=127.0.0.1 --mysqlx-bind-address=127.0.0.1 --disable-log-bin
    environment:
      MYSQL_DATABASE: school_web
    volumes:
      - /var/lib/school_web/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: .env
    network_mode: host
    environment:
      PMA_HOST: 127.0.0.1
      APACHE_PORT: 8010
      UPLOAD_LIMIT: 1024M
    depends_on:
      - mysql

  school-web:
    image: notmmdg/school-web
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/school_web:/var/lib/school_web
    depends_on:
      - mysql
