version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: school_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - school-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - school-network

  school-web:
    image: notmmdg/school-web
    container_name: school-web
    volumes:
      - /var/lib/school_web:/var/lib/school_web
      - /opt/school-web/.env:/app/.env
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - db
    networks:
      - school-network

volumes:
  db_data:

networks:
  school-network:
