"""Added Enroll class

Revision ID: 06afb2cf2a14
Revises: 82b49fb7527f
Create Date: 2024-07-29 14:28:48.190238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06afb2cf2a14'
down_revision = '82b49fb7527f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.Integer(), nullable=True),
    sa.Column('date_enrolled', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.CCode'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.SId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enroll_id'), 'enroll', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enroll_id'), table_name='enroll')
    op.drop_table('enroll')
    # ### end Alembic commands ###
