"""Added StudentSection and CollegeDept models

Revision ID: 2188c35c84bf
Revises: 
Create Date: 2024-07-29 13:48:27.513970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2188c35c84bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('BId', sa.Integer(), nullable=False),
    sa.Column('BTitle', sa.String(length=255), nullable=True),
    sa.Column('BAuthor', sa.String(length=255), nullable=True),
    sa.Column('BPubDate', sa.Date(), nullable=True),
    sa.Column('LCode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('BId')
    )
    op.create_index(op.f('ix_book_BId'), 'book', ['BId'], unique=False)
    op.create_index(op.f('ix_book_BTitle'), 'book', ['BTitle'], unique=False)
    op.create_table('college',
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('CName', sa.String(length=255), nullable=True),
    sa.Column('COffice', sa.Integer(), nullable=True),
    sa.Column('CPhone', sa.String(length=255), nullable=True),
    sa.Column('CDean', sa.Integer(), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('CID')
    )
    op.create_index(op.f('ix_college_CID'), 'college', ['CID'], unique=False)
    op.create_table('educational_employee',
    sa.Column('EId', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('eduID', sa.Integer(), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('EId')
    )
    op.create_index(op.f('ix_educational_employee_EId'), 'educational_employee', ['EId'], unique=False)
    op.create_table('room',
    sa.Column('RCode', sa.Integer(), nullable=False),
    sa.Column('RLocation', sa.String(length=255), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('RCode')
    )
    op.create_index(op.f('ix_room_RCode'), 'room', ['RCode'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dept',
    sa.Column('DCode', sa.Integer(), nullable=False),
    sa.Column('DName', sa.String(length=255), nullable=True),
    sa.Column('DOffice', sa.Integer(), nullable=True),
    sa.Column('DPhone', sa.String(length=255), nullable=True),
    sa.Column('CID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CID'], ['college.CID'], ),
    sa.PrimaryKeyConstraint('DCode')
    )
    op.create_index(op.f('ix_dept_DCode'), 'dept', ['DCode'], unique=False)
    op.create_table('college_dept',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.CID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_code'], ['dept.DCode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id', 'dept_code')
    )
    op.create_table('course',
    sa.Column('CCode', sa.Integer(), nullable=False),
    sa.Column('CoName', sa.String(length=255), nullable=True),
    sa.Column('Level', sa.String(length=255), nullable=True),
    sa.Column('CDesc', sa.String(length=255), nullable=True),
    sa.Column('DCode', sa.Integer(), nullable=True),
    sa.Column('Credit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DCode'], ['dept.DCode'], ),
    sa.PrimaryKeyConstraint('CCode')
    )
    op.create_index(op.f('ix_course_CCode'), 'course', ['CCode'], unique=False)
    op.create_table('employee',
    sa.Column('EId', sa.Integer(), nullable=False),
    sa.Column('Fname', sa.String(length=255), nullable=True),
    sa.Column('Lname', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('DCode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DCode'], ['dept.DCode'], ),
    sa.PrimaryKeyConstraint('EId')
    )
    op.create_index(op.f('ix_employee_EId'), 'employee', ['EId'], unique=False)
    op.create_table('professor',
    sa.Column('PId', sa.Integer(), nullable=False),
    sa.Column('Fname', sa.String(length=255), nullable=True),
    sa.Column('Lname', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=255), nullable=True),
    sa.Column('DCode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DCode'], ['dept.DCode'], ),
    sa.PrimaryKeyConstraint('PId')
    )
    op.create_index(op.f('ix_professor_PId'), 'professor', ['PId'], unique=False)
    op.create_table('student',
    sa.Column('SId', sa.Integer(), nullable=False),
    sa.Column('Fname', sa.String(length=255), nullable=True),
    sa.Column('Lname', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('DCode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DCode'], ['dept.DCode'], ),
    sa.PrimaryKeyConstraint('SId')
    )
    op.create_index(op.f('ix_student_SId'), 'student', ['SId'], unique=False)
    op.create_table('borrow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_BId', sa.Integer(), nullable=True),
    sa.Column('student_SId', sa.Integer(), nullable=True),
    sa.Column('dateOFBorrow', sa.Date(), nullable=True),
    sa.Column('returnTime', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_BId'], ['book.BId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_SId'], ['student.SId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('SecId', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Semester', sa.String(length=255), nullable=True),
    sa.Column('RCode', sa.Integer(), nullable=True),
    sa.Column('CCode', sa.Integer(), nullable=True),
    sa.Column('PId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CCode'], ['course.CCode'], ),
    sa.ForeignKeyConstraint(['PId'], ['professor.PId'], ),
    sa.ForeignKeyConstraint(['RCode'], ['room.RCode'], ),
    sa.PrimaryKeyConstraint('SecId')
    )
    op.create_index(op.f('ix_section_SecId'), 'section', ['SecId'], unique=False)
    op.create_table('takes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SId', sa.Integer(), nullable=True),
    sa.Column('CCode', sa.Integer(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Semester', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['CCode'], ['course.CCode'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SId'], ['student.SId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delete',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SId', sa.Integer(), nullable=True),
    sa.Column('SecId', sa.Integer(), nullable=True),
    sa.Column('Type', sa.Integer(), nullable=True),
    sa.Column('DOD', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['SId'], ['student.SId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SecId'], ['section.SecId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SId', sa.Integer(), nullable=True),
    sa.Column('SecId', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SId'], ['student.SId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SecId'], ['section.SecId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_section',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.SecId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.SId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_section')
    op.drop_table('grade')
    op.drop_table('delete')
    op.drop_table('takes')
    op.drop_index(op.f('ix_section_SecId'), table_name='section')
    op.drop_table('section')
    op.drop_table('borrow')
    op.drop_index(op.f('ix_student_SId'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_professor_PId'), table_name='professor')
    op.drop_table('professor')
    op.drop_index(op.f('ix_employee_EId'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_course_CCode'), table_name='course')
    op.drop_table('course')
    op.drop_table('college_dept')
    op.drop_index(op.f('ix_dept_DCode'), table_name='dept')
    op.drop_table('dept')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_room_RCode'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_educational_employee_EId'), table_name='educational_employee')
    op.drop_table('educational_employee')
    op.drop_index(op.f('ix_college_CID'), table_name='college')
    op.drop_table('college')
    op.drop_index(op.f('ix_book_BTitle'), table_name='book')
    op.drop_index(op.f('ix_book_BId'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
